In [ ]:
#import numpy
import numpy as np

In [ ]:
a = [1,2,3,4]
print(a)

[1, 2, 3, 4]


In [ ]:
type(a)

list

In [ ]:
arr = np.array(a)
arr

array([1, 2, 3, 4])

In [ ]:
arr + 3

array([4, 5, 6, 7])

In [ ]:
a = [1,'Ram',3.4,4]
a

[1, 'Ram', 3.4, 4]

In [ ]:
arr = np.array([1,'raju',3.5])
arr

array(['1', 'raju', '3.5'], dtype='<U21')

In [ ]:
arr.dtype

dtype('<U21')

In [ ]:
a = [[1,2,3],[2,3,4]]
a

[[1, 2, 3], [2, 3, 4]]

In [ ]:
arr = np.array(a)
arr

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
np.array(a,dtype='float')

array([[1., 2., 3.],
       [2., 3., 4.]])

In [ ]:
np.array(a,ndmin=10)

array([[[[[[[[[[1, 2, 3],
               [2, 3, 4]]]]]]]]]])

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr1.ndim

2

In [ ]:
arr1.shape

(2, 4)

In [ ]:
arr1.size

8

## Indexing and slicing

In [ ]:
arr = np.array([[1,2,3,4],[4,5,6,7]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
arr[0][0]

1

In [ ]:
arr = [1,2,3,4,5]
arr

[1, 2, 3, 4, 5]

In [ ]:
arr[0] = 10
arr

[10, 2, 3, 4, 5]

In [ ]:
arr [0 : 4]

[1, 2, 3, 4]

In [ ]:
arr = np.array([[1,2,3,4],[4,5,6,7]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
arr [0 : 2, 0 : 2]

array([[1, 2],
       [4, 5]])

In [ ]:
list(range(0,15.1))

TypeError: ignored

In [ ]:
np.arange(0,10.5,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
np.linspace(10,50,80,retstep=True)

(array([10.        , 10.6779661 , 11.3559322 , 12.03389831, 12.71186441,
        13.38983051, 14.06779661, 14.74576271, 15.42372881, 16.10169492,
        16.77966102, 17.45762712, 18.13559322, 18.81355932, 19.49152542,
        20.16949153, 20.84745763, 21.52542373, 22.20338983, 22.88135593,
        23.55932203, 24.23728814, 24.91525424, 25.59322034, 26.27118644,
        26.94915254, 27.62711864, 28.30508475, 28.98305085, 29.66101695,
        30.33898305, 31.01694915, 31.69491525, 32.37288136, 33.05084746,
        33.72881356, 34.40677966, 35.08474576, 35.76271186, 36.44067797,
        37.11864407, 37.79661017, 38.47457627, 39.15254237, 39.83050847,
        40.50847458, 41.18644068, 41.86440678, 42.54237288, 43.22033898,
        43.89830508, 44.57627119, 45.25423729, 45.93220339, 46.61016949,
        47.28813559, 47.96610169, 48.6440678 , 49.3220339 , 50.        ]),
 0.6779661016949152)

In [ ]:
np.zeros((3,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(4,3)

array([[0.10941129, 0.42712781, 0.22789103],
       [0.75552672, 0.94003969, 0.17899679],
       [0.1703391 , 0.00466802, 0.5592123 ],
       [0.68800185, 0.60344202, 0.12069507]])

In [ ]:
np.random.randint(2,size=10)

array([1, 1, 1, 0, 0, 0, 1, 0, 1, 1])

#Arithmatic operations

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
arr + 1

array([2, 3, 4, 5])

In [ ]:
arr - 2

array([-1,  0,  1,  2])

In [ ]:
arr * 2

array([2, 4, 6, 8])

In [ ]:
arr ** 2

array([ 1,  4,  9, 16])

In [ ]:
arr1 = np.array([5,6,7,8])
arr1

array([5, 6, 7, 8])

In [ ]:
arr * arr1

array([ 5, 12, 21, 32])

In [ ]:
arr = np.array([[1,2,3,4],[2,3,4,5]])
arr1 = np.array([1,2,3,4])

In [ ]:
arr + arr1

array([[2, 4, 6, 8],
       [3, 5, 7, 9]])

## Pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_html('https://en.wikipedia.org/wiki/States_and_union_territories_of_India')[2]

In [ ]:
df

States and union territories of India ordered by
0  Area Population GDP (per capita) Abbreviations...
1                                                vte

In [ ]:
marks = [96,88,79,74]
marks

[96, 88, 79, 74]

In [ ]:
pd.DataFrame(marks,columns=['Marks'])

Marks
0     96
1     88
2     79
3     74

In [ ]:
df1 = pd.DataFrame({'Name' : ['Raju','Rohit','Poonam','Raj'],
                    'SID' : [2,4,5,6],
                    'Marks' : [98,88,67,87]})
df1

Name  SID  Marks
0    Raju    2     98
1   Rohit    4     88
2  Poonam    5     67
3     Raj    6     87

In [ ]:
df1.columns

Index(['Name', 'SID', 'Marks'], dtype='object')

In [ ]:
df1.shape

(4, 3)

In [ ]:
df1.head(2)

Name  SID  Marks
0   Raju    2     98
1  Rohit    4     88

In [ ]:
df1.tail(1)

Name  SID  Marks
3  Raj    6     87

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   SID     4 non-null      int64 
 2   Marks   4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes


In [ ]:
df1 = pd.DataFrame({'Name' : ['Raju','Rohit','Poonam','Raj','Raju'],
                    'SID' : [2,4,5,6,np.nan],
                    'Maths' : [98,88,67,87,87],
                    'Physics' : [93,76,np.nan,89,74]})
df1

Name  SID  Maths  Physics
0    Raju  2.0     98     93.0
1   Rohit  4.0     88     76.0
2  Poonam  5.0     67      NaN
3     Raj  6.0     87     89.0
4    Raju  NaN     87     74.0

In [ ]:
df1.SID

0    2.0
1    4.0
2    5.0
3    6.0
4    NaN
Name: SID, dtype: float64

In [ ]:
df1[['Maths','Physics']]

Maths  Physics
0     98     93.0
1     88     76.0
2     67      NaN
3     87     89.0
4     87     74.0

In [ ]:
df1.iloc[0 : 3]

Name  SID  Maths  Physics
0    Raju  2.0     98     93.0
1   Rohit  4.0     88     76.0
2  Poonam  5.0     67      NaN

In [ ]:
df1.set_index('Name',inplace=True)

In [ ]:
df1.loc['Raju']

SID  Maths  Physics
Name                     
Raju  2.0     98     93.0
Raju  NaN     87     74.0

#Records of students who has scored more than 90 in maths

In [ ]:
df1[df1['Maths'] > 90]

Name  SID  Maths  Physics
0  Raju  2.0     98     93.0

In [ ]:
df1 [ (df1['Maths'] > 80) & (df1['Maths'] < 90) ]

SID  Maths  Physics
Name                      
Rohit  4.0     88     76.0
Raj    6.0     87     89.0
Raju   NaN     87     74.0

In [ ]:
df = pd.DataFrame({'Temp' : [23,34,45,32,43,32],
                  'City' : ['Mumbai','Banglore','Delhi','Mumbai','Banglore','Delhi']})
df

Temp      City
0    23    Mumbai
1    34  Banglore
2    45     Delhi
3    32    Mumbai
4    43  Banglore
5    32     Delhi

In [ ]:
grp = df.groupby('City')
grp

In [ ]:
for city,value in grp:
  print(city)
  print(value)

Banglore
   Temp      City
1    34  Banglore
4    43  Banglore
Delhi
   Temp   City
2    45  Delhi
5    32  Delhi
Mumbai
   Temp    City
0    23  Mumbai
3    32  Mumbai


In [ ]:
grp.get_group('Mumbai')

Temp    City
0    23  Mumbai
3    32  Mumbai

In [ ]:
df.groupby('City')['Temp'].mean()

City
Banglore    38.5
Delhi       38.5
Mumbai      27.5
Name: Temp, dtype: float64

In [ ]:
df = pd.DataFrame({'Temp' : [23,34,45,np.nan,np.nan,32,43,32,np.nan],
                  'City' : ['Mumbai','Banglore','banglore','Delhi','Mumbai','Banglore','Delhi','Banglore','Delhi']})
df

Temp      City
0  23.0    Mumbai
1  34.0  Banglore
2  45.0  banglore
3   NaN     Delhi
4   NaN    Mumbai
5  32.0  Banglore
6  43.0     Delhi
7  32.0  Banglore
8   NaN     Delhi

In [ ]:
df.isnull().sum()

Temp    2
City    0
dtype: int64

In [ ]:
df.dropna(axis=1,how='all')

Temp      City
0  23.0    Mumbai
1  34.0  Banglore
2  45.0     Delhi
3   NaN    Mumbai
4  32.0  Banglore
5  43.0     Delhi
6  32.0  Banglore
7   NaN     Delhi

In [ ]:
df

Temp      City
0  23.0    Mumbai
1  34.0  Banglore
2  45.0  banglore
3   NaN     Delhi
4   NaN    Mumbai
5  32.0  Banglore
6  43.0     Delhi
7  32.0  Banglore
8   NaN     Delhi

In [ ]:
df['Temp'].fillna(method='ffill')

0    23.0
1    34.0
2    45.0
3    45.0
4    45.0
5    32.0
6    43.0
7    32.0
8    32.0
Name: Temp, dtype: float64

In [ ]:
df['Temp'].fillna(method='bfill',limit=2)

0    23.0
1    34.0
2    45.0
3    32.0
4    32.0
5    32.0
6    43.0
7    32.0
8     NaN
Name: Temp, dtype: float64

In [ ]:
df.describe(include='all')

Temp   City
count    6.000000      9
unique        NaN      4
top           NaN  Delhi
freq          NaN      3
mean    34.833333    NaN
std      8.084965    NaN
min     23.000000    NaN
25%     32.000000    NaN
50%     33.000000    NaN
75%     40.750000    NaN
max     45.000000    NaN

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({"Name" : ['Jay','Ross','Brandon','Kayle','Rohit','Ravi','Jenny','Ram','Alice','Roy'],
                   "Maths" : [89,75,56,np.nan,65,78,79,69,98,65],
                   "Physics" : [79,56,np.nan,42,88,73,69,np.nan,85,74],
                   "Chemistry" : [88,79,68,75,88,72,np.nan,np.nan,98,65]})
print(df)

      Name  Maths  Physics  Chemistry
0      Jay   89.0     79.0       88.0
1     Ross   75.0     56.0       79.0
2  Brandon   56.0      NaN       68.0
3    Kayle    NaN     42.0       75.0
4    Rohit   65.0     88.0       88.0
5     Ravi   78.0     73.0       72.0
6    Jenny   79.0     69.0        NaN
7      Ram   69.0      NaN        NaN
8    Alice   98.0     85.0       98.0
9      Roy   65.0     74.0       65.0


In [ ]:
df1 = pd.DataFrame({'Name' : ['Sam'],
                    'Maths' : [79],
                    'Physics' : [80],
                    'Chemistry' : [77]})
df1

Name  Maths  Physics  Chemistry
0  Sam     79       80         77

In [ ]:
df.append(df1,ignore_index=True)

Name  Maths  Physics  Chemistry
0       Jay   89.0     79.0       88.0
1      Ross   75.0     56.0       79.0
2   Brandon   56.0      NaN       68.0
3     Kayle    NaN     42.0       75.0
4     Rohit   65.0     88.0       88.0
5      Ravi   78.0     73.0       72.0
6     Jenny   79.0     69.0        NaN
7       Ram   69.0      NaN        NaN
8     Alice   98.0     85.0       98.0
9       Roy   65.0     74.0       65.0
10      Sam   79.0     80.0       77.0

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                     'B': ['B4', 'B5', 'B6', 'B7'],
                     'C': ['C4', 'C5', 'C6', 'C7'],
                     'D': ['D4', 'D5', 'D6', 'D7']})

In [ ]:
pd.concat([df1,df2],ignore_index=True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
#Merge
left = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K13'], 
                    'A': ['A0', 'A1', 'A2', 'A3'], 
                    'B': ['B0', 'B1', 'B2', 'B3']}) 
  

In [ ]:
right = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K3'], 
                      'C': ['C0', 'C1', 'C2', 'C3'], 
                      'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
pd.merge(left,right,how='outer')

Key    A    B    C    D
0   K0   A0   B0   C0   D0
1   K1   A1   B1   C1   D1
2   K2   A2   B2   C2   D2
3  K13   A3   B3  NaN  NaN
4   K3  NaN  NaN   C3   D3